### PR TITLE
Hamiltonian monte carlo (HMC) sampling is available in MTUQ through SeisHMC

### PR DESCRIPTION
**Pull request by Liang-Ding**
Hamiltonian monte carlo (HMC) sampling is available in MTUQ through package SeisHMC.
(1) The data and 3D Greens function in folder ./data/examples/SPECFEM3D_SGT are updated.
(2) SeisHMC is added in MTUQ to enable HMC sampling.
(3) Two examples (test_HMC_DoubleCouple.py and test_HMC_FullMomentTensor.py) are provided in folder ./tests 
For more examples and details about SeisHMC, refer to https://github.com/Liang-Ding/seishmc.

### CODE REVIEW

**Comment by rmodrak** [comment]
It looks like a version conflict or other problem with pip itself may be causing the failed CI tests?

**Comment by Liang-Ding** [comment]
> 



> Looks great, thank Liang. How do the HMC and grid search results compare? Could be interesting to discuss.

Hi Ryan, here are two examples showing the comparison between MTUQ and HMC in moment tensor inversion (See also in https://github.com/Liang-Ding/seishmc)
HMC sampling can evaluate the solutions at the parameter space without relying on pre-defined grids. 
mtuq_vs_hmc_DC
mtuq_vs_hmc_FMT

**Comment by rmodrak** [comment]
Thank you for posting this great comparison!  Encouraging to see the multimodality over strike,dip,rake is well captured.   Looking forward to trying these kinds of tests on my end too.

**Comment by rmodrak** [comment]
For now, the CI tests seem to be failing for some reason related to the CI script itself, not to the pull request modifications.  Hoping I or others can this resolve this soon.

**Pull request merged**
