### PR TITLE
Polarity misfit

### PR DESCRIPTION
**Pull request by thurinj**
The polarity misfit implementation has been entirely reworked to allow more flexibility in terms of inputs.

The polarity misfit now accepts a greater range of input types, from lists and NumPy arrays of [1,0,-1] values, CAP weight file path (legacy mode, compatible with CAPUAF input styles), and mtuq.Dataset or mtuq.GreensTensorList with a correctly set SAC header. 
This update also grants flexibility in terms of header keyword choice, as it allows defining a custom keyword as input when initializing the polarity misfit object.

This new implementation also lets users specify a valid obspy.taup TauPyModel object to compute the takeoff angle in a 1D model on the fly, or will automatically read the takeoff angle written by FK in the green's function SAC header (in 'user1' field). If not provided, it will default to ak135.

The beachball_pygmt plot function has been updated accordingly, to reflect these changes and adopt the same automatic input management style.
The function relatives to on-the-fly computation of takeoff angle or observed polarity parsing, have been moved to a dedicated polarity script in the util folder.

An example has been added in the mtuq example folder.

### CODE REVIEW

**Comment by rmodrak** [comment]
Julien,

Thanks for the update last week and for this pull request.   Extremely useful!

We could accept the pull request now, with a note saying still under development.   Does this sound okay?   

If it's alright, I'd like to try my hand at the following.  Please let me know if I am misunderstanding anything.

Again, thanks very much.

Ryan


- Raise NotImplementedError for 3D Earth models
- Raise NotImplementedError for Force sources

- For reading takeoffs angle from FK metadata, follow the existing keyword argument names used by ProcessData
- If at all possible, not rely directly on SAC metadata for observed polarities; require an intermediate step instead
- Think further about how polarity generalizes to 3D models? (e.g. what if you have a caustic directly below the station)
- There are two competing implementations of plot_polarities - merge them

**Comment by rmodrak** [comment]
A few more thoughts

- I like how you overload the existing grid_search input arguments - it seems to work very well

- For 3D models, on-the-fly ray tracing may no longer be feasible.  Is it more sensible to get first-motion polarities from synthetic waveforms instead?  This is probably quite far down the road

**Comment by rmodrak** [comment]
Sounds, please feel free to merage whenever you like.

| forgot to add NotImplemented errors
More than just adding NotImplementedErrors,  I am wondering will the existing approach generalize to Forces and 3D models?  I think it will, but you may have a much better sense.

| Would you prefer that I take down the mtuq.Dataset and mtuq.GreensTensorList option out of the polarity misfit function call?
No, I think the current approach is very good.  I would just try to tweak it a bit.  Ideally, I want to not read directly on SAC headers, but maybe from a tag or attribute instead.  This would help me, because at work we are encouraged to read directly from a database, without writing intermediate SAC files to disk.  I could try iterating on this myself.

**Comment by thurinj** [comment]
Hi  Ryan,

As for this point:
>No, I think the current approach is very good. I would just try to tweak it a bit. Ideally, I want to not read directly from SAC headers, but maybe from a tag or attribute instead. This would help me, because at work we are encouraged to read directly from a database, without writing intermediate SAC files to disk. I could try iterating on this myself.

Provided you still rely on an obspy data structure once you read from the database, what do you think about writing/adding all the info we need in the `Stream.station`, instead of fetching info from `Trace.stats.sac`? Or do you have a different data structure to work with?

As for the force polarity, I'd have to check (is it as simple as positive within the half-sphere centered on the source vector direction, and negative on the other side of the sphere?), but we could potentially call a different function to compute radiation pattern (having a `radiation_coef_mt()` and `radiation_coef_force()`). 
For the 3D Green's function, I am not completely sure of what's the most straightforward approach since the takeoff angle is more involved to compute. But once we have it for each source-station pair, we don't have to do any more computation than getting the radiation coefficient from the source, which is straightforward.

**Pull request merged**
