### PR TITLE
SPECFEM3D_SGT to utilize the stored strain Green's tensor database for the inversion 

### PR DESCRIPTION
**Pull request by Liang-Ding**
'SPECFEM3D_SGT' client is available for the inversion which is able to generate Green's function based on the stored Strain Green's Tensor (SGT) database pre-computed by using 3D background models.

### CODE REVIEW

**Comment by rmodrak** [comment]
Thank you, this looks very nicely implemented.  I think we will learn a lot about how to very efficiently work with strain and other volumetric data.  Also, you are the first one to extend the package using the existing base classes.  Much appreciated!  I hope it was not too painful.   

Will dig into this much more and respond further.

**Comment by rmodrak** [comment]
There is still deeper to dig into the pull request details, but think I'm starting to get an overall sense.  

A lot of planning and coding effort has gone into working with these databases in an efficient way.  I think we will learn a lot from this.

The main work here is directly analogous to [instaseis](https://instaseis.net/), with a lot of similarity in terms of how synthetics are obtained from the saved output of a spectral element solver.

I wanted to raise the idea of hosting this strain GF database client within its own separate repo.   In terms of software engineering and long term maintenance, I think a separate repo could be very warranted.  I don't think it would take much time to set up.

Is this something you have considered by chance Liang?

Thanks,
Ryan

**Comment by Liang-Ding** [comment]
Hi Ryan,

Thank you for your suggestions.
It's okay that we first update the forked MTUQ package at my GitHub
repository and then pull requests to the mainstream if needed.
I will continue to update our code by using the class and functions that
are provided in the MTUQ.
Let me know if you have any questions and suggestions.

Cheers,
Liang

**Comment by rmodrak** [comment]
Rather than including the strain GF database client directly in MTUQ, my suggestion would be to create a standalone repo similar to instaseis.  The repo could be similar to instaseis in many respects, expect using SPECFEM3D output files rather than AxiSEM output files.

Does this sound like a good approach?  What do you think?

**Pull request merged**
