### PR TITLE
SPECFEM3D_SAC client support depth gridsearch 

### PR DESCRIPTION
**Pull request by SeismoFelix**
[SPECFEM3D_SAC.py](https://github.com/uafgeotools/mtuq/blob/0641750d67876cee49baa71b1f3320c96e10ffe1/mtuq/io/clients/SPECFEM3D_SAC.py) and [SPECFEM3D_SGT.py](https://github.com/uafgeotools/mtuq/blob/0641750d67876cee49baa71b1f3320c96e10ffe1/mtuq/io/clients/SPECFEM3D_SGT.py) client scripts were changed to support depth grid searches. In the MTUQ current version, when SPECFEM3D format is used, the path to the Green Functions (GFs) leads directly to the SAC files. Therefore, it is not possible to implement a moment tensor estimation, allowing a depth grid search. For instance, when using FK GFs, the path does not lead immediately to the SAC files but a manifold of directories named after the GFs database depth. To be consistent with the FK client, if this pull request is approved,  the SPECFEM3D (SAC and SGT) GFs have to be saved in a directory named after the earthquake depth (e.g., /User/SpecfemGFs/6/*.sac if the depth of the earthquake is 6km).

The SPECMFEM3D [examples data](https://github.com/uafgeotools/mtuq/tree/master/data/examples) tgz files were modified (SAC and SGT) to include the earthquake depth in the directory name. For instance: SPECFEM3D_SAC/20090407201255351 would be now SPECFEM3D_SAC/20090407201255351/33

The [test_greens_SPECFEM3D_SAC.py](https://github.com/uafgeotools/mtuq/blob/master/tests/test_greens_SPECFEM3D_SAC.py) and [test_greens_SPECFEM3D_SGT.py](https://github.com/uafgeotools/mtuq/blob/master/tests/test_greens_SPECFEM3D_SGT.py) scripts were modified for setting earthquake depths rounded to the nearest integer. This is for making the creation of the corresponding GFs directory easier (e.g., for a depth of 33033.599853515625, the GFs directory had to end in 33.0335... So, for simplicity, the depth was rounded to 33000)

The setup/code_generator.py script remains unmodified since (so far) it does not write test_greens_SPECFEM3D_SAC.py and test_greens_SPECFEM3D_SGT.py. 

With these modifications, the implementation of [GridSearch.DoubleCouple+Magnitude+Depth.py](https://github.com/uafgeotools/mtuq/blob/master/examples/GridSearch.DoubleCouple%2BMagnitude%2BDepth.py) for SPECFEM3D GFs is straightforward and was already tested.

### CODE REVIEW

**Comment by rmodrak** [comment]
Felix, 

Very useful, I think this is a big improvement.

I was thinking of trying the following--

- Allow either km or m for the subdirectory name,  to allow shallow searches
- Possibly try to implement in a way that is more backward compatible
- Also I think the docs may need to be updated

Is it alright if I make changes to your fork?

thanks,
Ryan

**Comment by SeismoFelix** [comment]
Sure! Be my guest. Is enough Clicking in the box 'Allow edits by maintainers' to allow you to work my fork. If so, go ahead, and thanks for the help.

**Comment by rmodrak** [comment]
Sounds good, I will go ahead.

**Comment by rmodrak** [comment]
Agreed, shallow searches can be helpful for underground explosions, implosions, etc.  I was thinking choosing between  m or km via an optional keyword argument. I believe the newly modified tgz files should continue to work fine.

**Comment by rmodrak** [comment]
I've tried revising [SPECFEM3D_SAC.py](https://github.com/SeismoFelix/mtuq/blob/ca03c67f7a9b835a922dc24913e2221f690d38ad/mtuq/io/clients/SPECFEM3D_SAC.py).  Could you glance at it?

**Comment by rmodrak** [comment]
I don't understand the propsed changes to [SPECFEM_SGT.py](https://github.com/SeismoFelix/mtuq/blob/ca03c67f7a9b835a922dc24913e2221f690d38ad/mtuq/io/clients/SPECFEM3D_SGT.py).

Doesn't the existing name convention already include depth? (see [line 118](https://github.com/SeismoFelix/mtuq/blob/ca03c67f7a9b835a922dc24913e2221f690d38ad/mtuq/io/clients/SPECFEM3D_SGT.py#L108))

**Comment by SeismoFelix** [comment]
> I don't understand the propsed changes to [SPECFEM3D_SGT.py](https://github.com/SeismoFelix/mtuq/blob/ca03c67f7a9b835a922dc24913e2221f690d38ad/mtuq/io/clients/SPECFEM3D_SGT.py).
> 
> Doesn't the existing name convention already include depth? (see [line 118](https://github.com/SeismoFelix/mtuq/blob/ca03c67f7a9b835a922dc24913e2221f690d38ad/mtuq/io/clients/SPECFEM3D_SGT.py#L108))

You are right Ryan, sorry. The SGT modifications are unnecessary since the name convention already includes the depth. I will put the SGT codes (SPECFEM3D_SGT.py, test_greens_SPECFEM3D_SGT.py, and the SGT GFs directory) in their original form.

**Review by rmodrak — APPROVED** [review]

**Comment by rmodrak** [comment]
Sounds great, thanks Felix.  Please feel free to merge whenever ready.

**Comment by SeismoFelix** [comment]
Great, Ryan, thanks. I already checked the moment tensor estimations with Specfem3D GFs, allowing depth search, and everything looks fine after your commit. However, I do not see the merge option below the message that there are no conflicts with the base branch. It seems I have no permission for merging. 

Screenshot 2023-11-09 at 1 44 17 PM

**Pull request merged**
