### PR TITLE
updated the examples using 3D SGT.

### PR DESCRIPTION
**Pull request by Liang-Ding**
Updated the data and code for the examples using the 3D SGT Greens Function

### CODE REVIEW

**Comment by rmodrak** [comment]
Hi Liang,

Thanks for updating the pull request.  

If you'd like these changes to be accepted immediately, could you simply comment out [this line](https://github.com/uafgeotools/mtuq/blob/453610fa8f193e13a33e2df7867ade472824b471/tests/check_examples.bash#L20)?

If you'd like someone to try out the example first, I could do it after I return from travel in a few days.

thanks,
Ryan

**Comment by Liang-Ding** [comment]
Hi Ryan,

Thanks for your note! 
Although we tested those examples in a Linux machine, that would be appreciated if you could verify them with your tests in other OS.

Thanks,
Liang

**Comment by rmodrak** [comment]
very exciting to see a working seiscloud example!

**Comment by rmodrak** [comment]
- could the seisclould Green's functions be downloaded to `data/greens_tensor/seiscloud`? (in this way, I was thinking we might avoid making changes to the TGZ file and thus adding another large binary file to the repo, and also maybe more closely follow the sygine implementation?)

- could we replace this block of code:
https://github.com/Liang-Ding/mtuq/blob/7467b8be1cb8dc65e4b86052c5252bf4fa81e88d/mtuq/io/clients/seiscloud.py#L135
with this instead:
https://github.com/uafgeotools/mtuq/blob/453610fa8f193e13a33e2df7867ade472824b471/mtuq/io/clients/SPECFEM3D_SGT.py#L127

**Review by rmodrak — APPROVED** [review]

**Pull request merged**
